---
image: node:10.15.3

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:master:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: Production
    url: https://ibrokemy.app/
  script:
    - $NVM_DIR/nvm.sh && nvm install 10.15.3 && nvm use 10.15.3
    - npm install
    - npm install netlify-cli
    - npm run build
    - ./node_modules/.bin/netlify -A "$YOUR_ACCESS_TOKEN" deploy --dir=dist -p
...
# vim: syntax=yaml et ts=2 sts=2 sw=2