---
stages:
  - deploy

deploy:master:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: Production
    url: https://ibrokemy.app/
  variables:
    BUILD_DIRECTORY: .
  script:
    - npm install
    - npm run build
    - cd dist
    - netlify -A "$YOUR_ACCESS_TOKEN" deploy
...
# vim: syntax=yaml et ts=2 sts=2 sw=2