---
image: node:10.15.3

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:master:
  stage: deploy
  only:
    - master
  environment:
    name: Production
    url: https://ibrokemy.app/
  script:
    - npm install
    - npm run build
    - ./node_modules/.bin/netlify deploy --dir=dist -p
...
# vim: syntax=yaml et ts=2 sts=2 sw=2
